### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by akezeth** [akezeth/Catalog-of-my-things#30]
Here is the link to the project: [Ruby Capstone Kanban board](https://github.com/akezeth/Catalog-of-my-things/projects/1)

We are 3 members of the team.

Members : 

Team member 1 => Hafiz Massam Tabraiz Khan
Team member 2 => Aklilu Mekonnen
Team member 3 => Binod Bhusal

**Comment by nahnahdev** [comment]
## Project Status: APPROVED :green_circle: 
Hi @akezeth  , @HafizMassamTabraizKhan  and @binodbhusal  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 🔥 
- Cards created for group tasks ✔️ 
- Tasks assigned equally ✔️ 
- All cards have points assigned ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
